### ISSUE TITLE
Error in xtfrm.data.frame(x) : cannot xtfrm data frames

### ISSUE THREAD

**Issue by StefanosVoglis** [abelson-lab/scATOMIC#10]
Hi,
I got a new error using the version 2.0 of the package.

When running the example workflow I get the following error message

> > cell_predictions <- run_scATOMIC(lung_cancer_demo_data)
[1] "Starting Layer 1"
Error in xtfrm.data.frame(x) : cannot xtfrm data frames

And in contrast to the vignette its not a warning but an error message and causes an interruption of the function.

Any ideas what the reason could be?

> R version 4.3.0 (2023-04-21 ucrt)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 11 x64 (build 22621)
> 
> Matrix products: default
> 
> 
> locale:
> [1] LC_COLLATE=German_Germany.utf8  LC_CTYPE=German_Germany.utf8    LC_MONETARY=German_Germany.utf8 LC_NUMERIC=C                   
> [5] LC_TIME=German_Germany.utf8    
> 
> time zone: Europe/Berlin
> tzcode source: internal
> 
> attached base packages:
> [1] parallel  stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] data.table_1.14.8     lubridate_1.9.2       forcats_1.0.0         stringr_1.5.0         dplyr_1.1.2           purrr_1.0.1          
>  [7] readr_2.1.4           tidyr_1.3.0           tibble_3.2.1          tidyverse_2.0.0       pbmcapply_1.5.1       DISCOtoolkit_1.0.0   
> [13] copykat_1.1.0         cutoff.scATOMIC_0.1.0 agrmt_1.42.8          SeuratObject_4.1.3    Seurat_4.3.0          Rmagic_2.0.3         
> [19] Matrix_1.5-4          reticulate_1.28       caret_6.0-94          lattice_0.21-8        ggplot2_3.4.2         randomForest_4.7-1.1 
> [25] scATOMIC_2.0.0       
> 
> loaded via a namespace (and not attached):
>   [1] RColorBrewer_1.1-3     rstudioapi_0.14        jsonlite_1.8.4         magrittr_2.0.3         spatstat.utils_3.0-3   rmarkdown_2.21        
>   [7] vctrs_0.6.2            ROCR_1.0-11            spatstat.explore_3.2-1 htmltools_0.5.5        pROC_1.18.2            sctransform_0.3.5     
>  [13] parallelly_1.35.0      KernSmooth_2.23-20     htmlwidgets_1.6.2      ica_1.0-3              plyr_1.8.8             plotly_4.10.1         
>  [19] zoo_1.8-12             igraph_1.4.2           mime_0.12              lifecycle_1.0.3        iterators_1.0.14       pkgconfig_2.0.3       
>  [25] R6_2.5.1               fastmap_1.1.1          fitdistrplus_1.1-11    future_1.32.0          shiny_1.7.4            digest_0.6.31         
>  [31] colorspace_2.1-0       patchwork_1.1.2        rprojroot_2.0.3        tensor_1.5             irlba_2.3.5.1          progressr_0.13.0      
>  [37] fansi_1.0.4            spatstat.sparse_3.0-1  timechange_0.2.0       polyclip_1.10-4        httr_1.4.6             abind_1.4-5           
>  [43] compiler_4.3.0         here_1.0.1             withr_2.5.0            MASS_7.3-58.4          lava_1.7.2.1           rappdirs_0.3.3        
>  [49] ModelMetrics_1.2.2.2   tools_4.3.0            lmtest_0.9-40          httpuv_1.6.11          future.apply_1.10.0    goftest_1.2-3         
>  [55] nnet_7.3-18            glue_1.6.2             nlme_3.1-162           promises_1.2.0.1       grid_4.3.0             Rtsne_0.16            
>  [61] cluster_2.1.4          reshape2_1.4.4         generics_0.1.3         recipes_1.0.6          gtable_0.3.3           spatstat.data_3.0-1   
>  [67] tzdb_0.4.0             class_7.3-21           hms_1.1.3              sp_1.6-0               utf8_1.2.3             spatstat.geom_3.2-1   
>  [73] RcppAnnoy_0.0.20       ggrepel_0.9.3          RANN_2.6.1             foreach_1.5.2          pillar_1.9.0           later_1.3.1           
>  [79] splines_4.3.0          deldir_1.0-9           survival_3.5-5         tidyselect_1.2.0       miniUI_0.1.1.1         pbapply_1.7-0         
>  [85] knitr_1.42             gridExtra_2.3          scattermore_1.1        stats4_4.3.0           xfun_0.39              hardhat_1.3.0         
>  [91] timeDate_4022.108      matrixStats_0.63.0     stringi_1.7.12         lazyeval_0.2.2         yaml_2.3.7             evaluate_0.21         
>  [97] codetools_0.2-19       cli_3.6.1              uwot_0.1.14            rpart_4.1.19           xtable_1.8-4           munsell_0.5.0         
> [103] Rcpp_1.0.10            spatstat.random_3.1-5  globals_0.16.2         png_0.1-8              ellipsis_0.3.2         gower_1.0.1           
> [109] listenv_0.9.0          viridisLite_0.4.2      ipred_0.9-14           scales_1.2.1           prodlim_2023.03.31     ggridges_0.5.4        
> [115] leiden_0.4.3           rlang_1.1.1            cowplot_1.1.1

**Comment by inofechm** [comment]
Hi Stefanos,
Thank you for bringing up this issue! I believe what was once a warning in R versions < 4.3 is now an error.
I will work on a fix ASAP and update the package

**Comment by inofechm** [comment]
Hi Stefanos,
I have modified the code to avoid this error/warning.
Could you please re-install scATOMIC version 2.0.1 with `devtools::install_github("abelson-lab/scATOMIC")`
Let me know if the workflow works on your end now and I'll close the issue
Thanks again for raising this important issue

**Comment by StefanosVoglis** [comment]
Hi,
now it works! Many thanks!
