### ISSUE TITLE
Question about "known_cancer_type"

### ISSUE THREAD

**Issue by liangxs7015** [abelson-lab/scATOMIC#29]
Hi, thanks for your wonderful tool to solve cancer scRNA annotation issue.

When I 'm using scATOMIC to annotate my cancer samples, I came up with a question that should I use the cancer type strings from the list :
 '"Bile Duct Cancer Cell", "Bladder Cancer Cell", "Bone Cancer Cell", "Brain Cancer Cell", "Breast Cancer Cell", "Colon/Colorectal Cancer Cell", "Endometrial/Uterine Cancer Cell", "Esophageal Cancer Cell", "Gallbladder Cancer Cell", "Gastric Cancer Cell", "Kidney Cancer Cell", "Liver Cancer Cell", "Lung Cancer Cell", "Neuroblastoma", "Ovarian Cancer Cell", "Pancreatic Cancer Cell", "Prostate Cancer Cell", "Sarcoma", "Skin Cancer Cell", "Breast/Lung/Prostate", "Ovarian/Endometrial/Kidney", "Endometrial Cancer Cell", "Biliary/Hepatic Cancer Cell", "Brain/Neuroblastoma Cancer Cell", "Digestive Tract Cancer Cell", "Soft Tissue Cancer Cell", "Soft Tissue or Neuro Cancer Cell", "Unclassified Soft Tissue or Neuro Cancer Cell", "ER+ Breast Cancer Cell", "HER2+ Breast Cancer Cell", "Her2+ Breast Cancer Cell", "TNBC Breast Cancer Cell",  "Epithelial Cell", "GI Tract Cell"'?  

Because I noticed that you stated that only "bladder, brain, breast, colorectal, kidney, liver, lung, neuroblastoma, ovarian, pancreatic, prostate, sarcoma, and skin cancers" are included in your training set. Has the number of cancer type been extended since then? Thanks a lot for your help!

**Comment by inofechm** [comment]
Hello thanks for your interest in our work.

> Because I noticed that you stated that only "bladder, brain, breast, colorectal, kidney, liver, lung, neuroblastoma, ovarian, pancreatic, prostate, sarcoma, and skin cancers"

These are the cancer types that we validated in multiple external cohorts in our paper.

The other cancer types like Bile Duct, Endometrial etc. are cancers that scATOMIC is trained to classify but there was not sufficient datasets for full external validation at the time of the publication, but the model is trained to predict them.

You can find this list in the hierarchy in figure 1 of the paper.

Currently we have not added any other cancer types but may in the future.

Ido

**Comment by liangxs7015** [comment]
> Hello thanks for your interest in our work.
> 
> > Because I noticed that you stated that only "bladder, brain, breast, colorectal, kidney, liver, lung, neuroblastoma, ovarian, pancreatic, prostate, sarcoma, and skin cancers"
> 
> These are the cancer types that we validated in multiple external cohorts in our paper.
> 
> The other cancer types like Bile Duct, Endometrial etc. are cancers that scATOMIC is trained to classify but there was not sufficient datasets for full external validation at the time of the publication, but the model is trained to predict them.
> 
> You can find this list in the hierarchy in figure 1 of the paper.
> 
> Currently we have not added any other cancer types but may in the future.
> 
> Ido

Okay, many thanks for your reply, I am now trying to annotate 13 cancer types and waiting to see the results
