### ISSUE TITLE
Issue and solution with devtools::install_github("abelson-lab/scATOMIC")

### ISSUE THREAD

**Issue by Bellanzixuan** [abelson-lab/scATOMIC#3]
In case：
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/abelson-lab/scATOMIC/tarball/HEAD' failed
Try:
options(timeout=9999999)
Then:
devtools::install_github("abelson-lab/scATOMIC")

**Comment by inofechm** [comment]
Thanks added to the tutorial section on installation!
