### ISSUE TITLE
"arguments imply differing number of rows" error - run_scATOMIC function call 

### ISSUE THREAD

**Issue by StefanosVoglis** [abelson-lab/scATOMIC#4]
Hi there,
thank you for the great package an congratulations for the publication!

Unfortunately I am running in an error when trying the package with my own dataset. (demo_lung_data works so far).

```
sparse_matrix <- rna.final@assays$RNA@counts

cell_predictions <- run_scATOMIC(sparse_matrix, imputation = F)
```

Results in the following error message:

> Warning in parallel::mclapply(row.names(predictions), scATOMIC::class_for_cutoff,  :
  scheduled core 19 encountered error in user code, all values of the job will be affected
Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 7209, 7210

`traceback()`

> 7: stop(gettextf("arguments imply differing number of rows: %s", 
       paste(unique(nrows), collapse = ", ")), domain = NA)
6: data.frame(..., check.names = FALSE)
5: cbind(deparse.level, ...)
4: cbind(na.omit(predictions), cutoff_class)
3: get_auto_threshold(layer_predictions)
2: scATOMIC::classify_layer(rna_counts = rna_counts, cells_to_use = TNK_cells_predicted, 
       layer = "layer_3_TNK", imputation = F, genes_in_model = top_genes_unlisted_layer_3_TNK, 
       model = model_layer_3_TNK, ref_based = ref_based, mc.cores = mc.cores, 
       unimodal_nsd = unimodal_nsd, bimodal_nsd = bimodal_nsd, normalized_counts = normalized_counts)
1: run_scATOMIC(sparse_matrix, imputation = F, mc.cores = 1)

Any ideas what this might cause?

Thanks in advance!

Best, 
Stefanos

**Comment by inofechm** [comment]
Hi Stefanos,
Thank you for the kind words and for raising the issue.
It looks like there may be an issue with a low quality cell being filtered out in the T-NK layer of classification.
Can you see if it works with imputation set to true?

For me to fully de-bug this and update the code accordingly I might need to take a look at your data, if you are willing to share it. 

I will update you shortly once I check the code

**Comment by StefanosVoglis** [comment]
Hey ! 
Thanks for your quick reply.

Unfortunately the impute = T function does not work. R ression always crashes without any error message. 

I use the following code as provided in the example:
```
lung_cancer_demo_data <- demo_lung_data
pct_mt <- colSums(lung_cancer_demo_data[grep("^MT-", row.names(lung_cancer_demo_data)),])/colSums(lung_cancer_demo_data) * 100
nFeatureRNA <- colSums(lung_cancer_demo_data > 0)
lung_cancer_demo_data <- lung_cancer_demo_data[, names(which(pct_mt < 25))]
lung_cancer_demo_data <- lung_cancer_demo_data[, intersect(names(which(nFeatureRNA > 500)), colnames(lung_cancer_demo_data))]

cell_predictions <- run_scATOMIC(lung_cancer_demo_data, imputation = T)
```

And RMagic / pymagic seems to be available.
> > pymagic_is_available()

> [1] TRUE

Same happens if I set `create_summary_matri(modify_results = T)`. R crashes without any error message.. 

Any ideas why this happens?

Kind regards, 

> R version 4.2.1 (2022-06-23)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 20.04.4 LTS
> 
> Matrix products: default
> BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
> LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/liblapack.so.3
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] parallel  stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] copykat_1.1.0         cutoff_0.1.0          agrmt_1.42.8          Rmagic_2.0.3          Matrix_1.5-3         
>  [6] reticulate_1.28       caret_6.0-94          lattice_0.20-45       randomForest_4.7-1.1  plyr_1.8.8           
> [11] scATOMIC_1.1.0        lubridate_1.9.2       forcats_1.0.0         stringr_1.5.0         dplyr_1.1.1          
> [16] purrr_1.0.1           readr_2.1.4           tidyr_1.3.0           tibble_3.2.1          ggplot2_3.4.1        
> [21] tidyverse_2.0.0       pbmcapply_1.5.1       FastIntegration_1.1.0 data.table_1.14.8     SeuratObject_4.1.3   
> [26] Seurat_4.3.0         
> 
> loaded via a namespace (and not attached):
>   [1] utf8_1.2.3                  shinydashboard_0.7.2        spatstat.explore_3.1-0      R.utils_2.12.2             
>   [5] tidyselect_1.2.0            htmlwidgets_1.6.2           grid_4.2.1                  BiocParallel_1.32.6        
>   [9] Rtsne_0.16                  pROC_1.18.0                 DropletUtils_1.18.1         munsell_0.5.0              
>  [13] codetools_0.2-19            ica_1.0-3                   future_1.32.0               miniUI_0.1.1.1             
>  [17] withr_2.5.0                 spatstat.random_3.1-4       colorspace_2.1-0            progressr_0.13.0           
>  [21] Biobase_2.58.0              knitr_1.42                  rstudioapi_0.14             stats4_4.2.1               
>  [25] SingleCellExperiment_1.20.1 ROCR_1.0-11                 tensor_1.5                  listenv_0.9.0              
>  [29] MatrixGenerics_1.10.0       GenomeInfoDbData_1.2.9      polyclip_1.10-4             rhdf5_2.42.0               
>  [33] rprojroot_2.0.3             parallelly_1.35.0           vctrs_0.6.1                 generics_0.1.3             
>  [37] ipred_0.9-14                xfun_0.38                   timechange_0.2.0            R6_2.5.1                   
>  [41] GenomeInfoDb_1.34.9         ggbeeswarm_0.7.1            RcppEigen_0.3.3.9.3         locfit_1.5-9.7             
>  [45] RcppZiggurat_0.1.6          bitops_1.0-7                rhdf5filters_1.10.0         spatstat.utils_3.0-2       
>  [49] DelayedArray_0.24.0         promises_1.2.0.1            scales_1.2.1                nnet_7.3-18                
>  [53] beeswarm_0.4.0              gtable_0.3.3                beachmat_2.14.0             globals_0.16.2             
>  [57] goftest_1.2-3               timeDate_4022.108           tictoc_1.1                  rlang_1.1.0                
>  [61] systemfonts_1.0.4           splines_4.2.1               lazyeval_0.2.2              ModelMetrics_1.2.2.2       
>  [65] spatstat.geom_3.1-0         yaml_2.3.7                  reshape2_1.4.4              abind_1.4-5                
>  [69] Rfast_2.0.7                 httpuv_1.6.9                lava_1.7.2.1                tools_4.2.1                
>  [73] SpatialExperiment_1.8.1     ellipsis_0.3.2              raster_3.6-20               RColorBrewer_1.1-3         
>  [77] BiocGenerics_0.44.0         ggridges_0.5.4              Rcpp_1.0.10                 sparseMatrixStats_1.10.0   
>  [81] zlibbioc_1.44.0             RCurl_1.98-1.10             rpart_4.1.19                deldir_1.0-6               
>  [85] pbapply_1.7-0               viridis_0.6.2               cowplot_1.1.1               S4Vectors_0.36.2           
>  [89] zoo_1.8-11                  SummarizedExperiment_1.28.0 ggrepel_0.9.3               cluster_2.1.4              
>  [93] here_1.0.1                  magrittr_2.0.3              magick_2.7.4                scattermore_0.8            
>  [97] lmtest_0.9-40               RANN_2.6.1                  fitdistrplus_1.1-8          matrixStats_0.63.0         
> [101] hms_1.1.3                   patchwork_1.1.2             mime_0.12                   fftwtools_0.9-11           
> [105] evaluate_0.20               xtable_1.8-4                jpeg_0.1-10                 IRanges_2.32.0             
> [109] gridExtra_2.3               compiler_4.2.1              KernSmooth_2.23-20          R.oo_1.25.0                
> [113] htmltools_0.5.5             tzdb_0.3.0                  later_1.3.0                 tiff_0.1-11                
> [117] rappdirs_0.3.3              MASS_7.3-58.3               cli_3.6.1                   R.methodsS3_1.8.2          
> [121] gower_1.0.1                 cytomapper_1.10.1           igraph_1.4.1                GenomicRanges_1.50.2       
> [125] pkgconfig_2.0.3             sp_1.6-0                    recipes_1.0.5               terra_1.7-18               
> [129] plotly_4.10.1               scuttle_1.8.4               spatstat.sparse_3.0-1       foreach_1.5.2              
> [133] svglite_2.1.1               hardhat_1.2.0               vipor_0.4.5                 dqrng_0.3.0                
> [137] XVector_0.38.0              prodlim_2019.11.13          digest_0.6.31               sctransform_0.3.5          
> [141] RcppAnnoy_0.0.20            spatstat.data_3.0-1         rmarkdown_2.20              leiden_0.4.3               
> [145] uwot_0.1.14                 edgeR_3.40.2                DelayedMatrixStats_1.20.0   shiny_1.7.4                
> [149] EBImage_4.40.0              rjson_0.2.21                lifecycle_1.0.3             nlme_3.1-162               
> [153] jsonlite_1.8.4              Rhdf5lib_1.20.0             viridisLite_0.4.1           limma_3.54.2               
> [157] fansi_1.0.4                 pillar_1.9.0                fastmap_1.1.1               httr_1.4.5                 
> [161] survival_3.5-5              glue_1.6.2                  iterators_1.0.14            png_0.1-8                  
> [165] svgPanZoom_0.3.4            class_7.3-21                stringi_1.7.12              HDF5Array_1.26.0           
> [169] nnls_1.4                    irlba_2.3.5.1               future.apply_1.10.0

**Comment by inofechm** [comment]
I think I've found the bug leading to your first issue and have updated the package.
Can you re-install scATOMIC with install_github and please let me know if this fix worked?
Otherwise I might need to look at your data to resolve this.

Regarding your issue with RMagic, sometimes you need to just need restart your R session after installation of RMagic, but generally once pymagic_is_available() it has worked for me.
I wonder if this is just an issue with the RMagic package and not scATOMIC, can you restart your R session and see if you are able to run:
`library(Rmagic)
data(magic_testdata)
data_MAGIC <- magic(magic_testdata)`

Thank you

**Comment by StefanosVoglis** [comment]
Thanks for the bugfix. Unfortunately for me the same error persists after re-installing the package and restarting the R session.

Regarding Rmagic:
I can run the code, with the following output:

> Calculating MAGIC...
>   Running MAGIC on 500 cells and 197 genes.
>   Calculating graph and diffusion operator...
>     Calculating PCA...
and then the session crashes without any error code...

**Comment by inofechm** [comment]
Thanks for trying again, unfortunately, it is hard for me to diagnose the issue without taking looking at the data you are trying to use. 
Is it still producing the same exact error?

Regarding the Rmagic issues, it looks like there is an issue on your machine's interface with that package, I've never seen it before, perhaps it is an issue with the version of the other python modules. It seems like someone had this issue in the past and this was the suggestion by the magic developers:
[https://github.com/KrishnaswamyLab/MAGIC/issues/118](url)

If possible could you please send me an email at inofechmozes@oicr.on.ca to discuss potentially taking a look at your dataset to understand the issue or setting up a quick call to diagnose the issue without having to do a data transfer?

**Comment by inofechm** [comment]
Hi @StefanosVoglis,

I am wondering if you had the same issue as #6 .
He had a similar error and it ended up having to do with not having a graphics card on his ubuntu 20.04 machine leading to issues when running the code in Rstudio. 
However using command line interactive mode R the error did not persist and the MAGIC diagnostic code worked.

Can you try running that diagnosis in command line R and reporting to me if that solved it?

Thanks,
Ido
