### ISSUE TITLE
Usage of tool for mouse models

### ISSUE THREAD

**Issue by Lucas-Maciel** [abelson-lab/scATOMIC#9]
Hi,

I was wondering if you have ever tested your tool in tumors from mouse models and if you have any recommendations. 

Thanks

**Comment by inofechm** [comment]
Hi Lucas,
we have not tried using scATOMIC in mice beyond exploratory contexts.
I think it could potentially work if we just convert the mouse input count matrices to human orthologues.
I think this code could do that [https://www.r-bloggers.com/2016/10/converting-mouse-to-human-gene-names-with-biomart-package/](url).

When I have some free time I can try this, but in the meantime if you try to do this please let me know if it is sucessful.

Thanks for your interest in scATOMIC!

**Comment by Lucas-Maciel** [comment]
I have a melanoma model, which based on an initial manual curation of clusters I identified that 25% are cancer cells.  scATOMIC predicted that 75% of my cells are Bladder Cancer cells. This cancer cells include the 25% that I identified before but also include many keratinocytes/CAFs.

```
table(results_melanoma$scATOMIC_pred)

         Bladder Cancer Cell                   Blood Cell                       CAFadi                     CAFinfla 
                        2985                            2                          115                           64 
                      CAFmyo                  CD4+ T cell                         cDC2 Effector/Memory CD4+ T cells 
                          40                            4                           25                           83 
Effector/Memory CD8+ T cells            Endothelial Cells                   Macrophage           Naive CD4+ T cells 
                          67                           67                           18                            7 
         Natural killer cell               Non Blood Cell             Non Stromal Cell            Normal Fibroblast 
                           2                            4                          194                           59 
     Phagocytosis Macrophage  Pro-angiogenesis Macrophage 
                          31                           17 
```
